name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 18.x, 14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Update npm to latest
      run: npm install -g npm@latest

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci

    - name: Show npm log on error
      if: failure()
      run: cat /home/runner/.npm/_logs/*-debug.log

    - name: Build project
      run: npm run build --if-present

    - name: Run tests
      run: npm test
